layout_spectrum: 0.115213
typography_spectrum: 0.8330816
color:
  lightness: 0.8816331
  brandStrength: 0.2643965
  saturation: 0.7996621
  rhythmicContrast: 0.1494941
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: South Mountain Journal
