layout_spectrum: 0.8148936
name: South Mountain Journal
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2643965
  saturation: 0.7996621
  lightness: 0.8816331
  rhythmicContrast: 0.1494941
typography_spectrum: 0.8330816
